---

state:
  code: RR
  name: Roraima
  region: Norte
  capital: Boa Vista
  cities:
    - Alto Alegre
    - Amajari
    - Boa Vista
    - Bonfim
    - Cantá
    - Caracaraí
    - Caroebe
    - Iracema
    - Mucajaí
    - Normandia
    - Pacaraima
    - Rorainópolis
    - São João da Baliza
    - São Luiz
    - Uiramutã

