FROM ruby:3.3.0-bookworm

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev libvips pkg-config

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock /usr/src/app/

ENV BUNDLE_PATH /gems

RUN bundle install --jobs 3

COPY . /usr/src/app/

