version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env/database
    networks:
      - my_network
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:8.11.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - my_network

  pubman:
    container_name: pubman
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /usr/src/app
    command: sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env/database
      - .env/app
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - db
      - elasticsearch

volumes:
  gem_cache:

networks:
  my_network:
    driver: bridge
